config/routes.rb
Rails.application.routes.draw do


devise_for :users

  resources :users do
	resources :photos, only: [:create]
  end
  root 'events#index'
  post 'events/subscribe/:id', to: 'events#subscribe', as: 'event_subscribe'

resources :attendances, only: [:index,:show,:new, :create]

resources :events do
	resources :avatars, only: [:create]
end

resources :charges

  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	after_create :welcome_attendees_send

	belongs_to :user
	belongs_to :event

	def welcome_attendees_send

		AttendanceMailer.welcome_attendees(self).deliver_now

	end



end

app/models/event.rb
class Event < ApplicationRecord
  has_one_attached :avatar
	belongs_to :admin, :foreign_key => :admin_id, class_name: 'User'
  belongs_to :attendee, :foreign_key => :attendee_id, class_name: 'User', optional: true
  has_many :attendances
  has_many :users, through: :attendances

  validates :avatar, presence: true
   validates :start_date, presence: true
   validate :future_event
   validates :duration, presence: true, numericality: {greater_than: 0}
   validate :multiple_of_5
   validates :title, presence: true, length: { minimum: 5, maximum: 140}
   validates :description, presence: true, length: { minimum: 20, maximum: 1000}
   validates :price, presence: true, numericality: {less_than: 1000}
   validates :location, presence: true
   
   def mois
    start_date.strftime("%^b")
  end
  def jour
    start_date.strftime('%d')
  end

   def message_time
      start_date.strftime("%d %^b %y | %l:%M %p")
    end
    def the_end
         @end = (start_date + duration.minute)
           @the_end = @end.strftime("%d %^b %y | %l:%M %p")
     end

   def is_free?
   self.price == 0
    
   end

   private



  def future_event
    if start_date == nil
      puts "Vous devez renseigner une date de debut"
    else
    errors.add(:date, "Can't be in the past!") if start_date < Time.now
  end
  end

  def multiple_of_5
    if duration == nil
    puts "Vous dvez renseignez une durée"
    else
  	errors.add(:duration, "must be a multiple of 5") if (duration % 5) != 0
    end
  end
 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

	after_create :welcome_send
	
	has_many :attendances
  has_many :events, through: :attendances
  has_many :created_events, class_name: "Event", foreign_key: 'admin_id'
  has_many :attended_events, class_name: "Event", foreign_key: 'attendee_id'



  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include UsersHelper
	def configure_devise_parameters
  devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :email, :password, :password_confirmation)}
end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end


end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController


	def create
    @event = Event.find(params[:event_id])
    @event.avatar.attach(params[:avatar])
    if @event.avatar.save
    	flash[:alert] = "Photo successfully added"
    redirect_to events_path
  end
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
  end

def create

end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :authenticate_user!, only: [:new]
	def index
		@event = Event.all
	end

	def new
		@new_event = Event.new
		@new_event.avatar.attach(params[:avatar])
	end

	def create
		@user = current_user.id
		@new_event = Event.new(event_params)
		if @new_event.save
			redirect_to root_path, alert: 'Votre événement a bien été créé'
		else
			render 'new'
		end
	end
	def edit
		@event = Event.find(params[:id])
		@event_update = Event.find(params['id'])

	end

	def update
		@user = current_user
		@event_update = Event.find(params[:id])
		if @event_update.update('start_date' => params[:start_date], 'duration' => params[:duration], 'title' => params[:title], 'description' => params[:description], 'price' => params[:price], 'location' => params[:location], 'admin_id' => @user.id)
			redirect_to root_path, alert: 'Votre potin a bien été mis à jour'
		else
			render :edit
		end
	end

	def destroy
		@event_destroy = Event.find(params[:id])
		@event_destroy.destroy
		redirect_to root_path, alert: 'Votre potin a bien été supprimé, bravo !'
	end

	def show
		@event = Event.find(params[:id])
	end

	def subscribe
		@event = Event.find(params[:id])
		@attendance = Attendance.new(stripe_customer_id: params[:stripeToken], event: @event, user_id: current_user.id)


		if @event.users.include? current_user
			flash[:error] = "Vous participez deja a l'événement"
			redirect_to event_path(params[:id])
			return 
		end
		@amount = @event.price

		customer = Stripe::Customer.create({
			email: params[:stripeEmail],
			source: params[:stripeToken],
		})

		charge = Stripe::Charge.create({
			customer: customer.id,
			amount: @amount * 100,
			description: 'Rails Stripe customer',
			currency: 'eur',
		})

		if @attendance.save
			flash[:succes] = "Vous êtes bien inscit a l'événement"
			redirect_to event_path(params[:id])
		end

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_charge_path
	end
	private
	def event_params
		params.permit(:start_date, :duration, :title, :description, :price, :location, :admin_id, :avatar)

	end
	def is_admin?
		@event.admin == current_user
	end

	def deja_participant?
		@event.users.include?(current_user) ? true : false
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
	  def create
    @user = User.find(params[:user_id])
    @user.photo.attach(params[:photo])
    redirect_to(user_path(@user))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show, :edit, :update]
  before_action :user_signed_in?, only: [:edit]
  def show
  	@user = User.find(params[:id])

  	@event = Event.all.where(admin: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy

  end

  

  def update
    @user = current_user
    if @user.update('first_name' => params[:first_name], 'last_name' => params[:last_name])
      redirect_to user_path(current_user.id), alert: 'Profil updated'
    else 
      render 'edit'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def avatar_for(user)
    @avatar = current_user.avatar
    if @avatar.empty?
        @avatar_user = image_tag("user.png")
    else
        @avatar_user = image_tag(@avatar)
    end
    return @avatar_user
end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper

	 
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/photosdp_helper.rb
module PhotosdpHelper
end

app/helpers/users_helper.rb
module UsersHelper
		def deja_participant?
      @attendance = Attendance.where(event_id: params[:id])
       if @attendance.user_id == current_user.id
       	return true
       else
       	return false
       end
    end
end

app/views/attendances/create.html.erb
<h1>Attendances#create</h1>
<p>Find me in app/views/attendances/create.html.erb</p>

app/views/attendances/index.html.erb
<h1>Attendances#index</h1>
<p>Find me in app/views/attendances/index.html.erb</p>

app/views/attendances/new.html.erb
<h1>Attendances#new</h1>
<p>Find me in app/views/attendances/new.html.erb</p>

app/views/attendances/show.html.erb
<h1>Attendances#show</h1>
<p>Find me in app/views/attendances/show.html.erb</p>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%=@amount%></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<br>
<%if @event_update.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
 <p><strong>Hola muchachos !</strong>  Nous n'avons pas réussi à modifier l'événement pour la (ou les) raison(s) suivante(s) :</p>
 <% @event_update.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>

 <button type="button" class="close" data-dismiss="alert" aria-label="Close">
  <span aria-hidden="true">&times;</span>
</button>
</div>
<%end%>

<div class="jumbotron jumbotron-fluid jumboedit">
  <h1 class="display-3 text-white" style="margin-left: 20px;">Edite cet événement</h1>
  <p class="display-3 text-white" style="margin-left: 20px;"></p>
  <p class="lead text-white" style="margin-left: 20px;"></p>

  <a class="btn btn-primary btn-lg" href="#form" role="button" style="margin-left: 20px;">Learn more</a>
</div>

<body>
  <!-- ... -->

  <div class="container">

    <%=form_tag url_for(action: 'update'), method: "put" do %>

    <form >
      <div id="form" class="form-row" style="width: 70%; margin: auto;">
        <div class="form-group col-md-6">
          <label for="inputEmail4">Title</label>
          <%= text_field_tag 'title', @event_update.title, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <label for="inputPassword4">Description</label>
          <%= text_field_tag 'description', @event_update.description, class: "form-control" %>
        </div>
      </div>

      <div class="form-row" style="width: 70%; margin: auto;">
        <div class="form-group col-md-6">
          <label>Duration</label>
          <%= number_field_tag 'duration', @event_update.duration, class: "form-control" %> 
        </div>

        <div class="form-group col-md-6">
          <label for="inputAddress2">Start date</label>
          <%= date_field_tag 'start_date', @event_update.start_date, class: "form-control" %>
        </div>
      </div>

      <div class="form-row" style="width: 70%; margin: auto;">
        <div class="form-group col-md-6">
          <label for="inputCity">Price</label>
          <%= number_field_tag'price', @event_update.price, class: "form-control" %>
        </div>
        <div class="form-group col-md-6">
          <label for="inputCity">Location</label>
          <%= text_field_tag 'location', @event_update.location, class: "form-control" %>
        </div>
      </div>
        <div>
          <br>
          <center><p type="submit" style="width: 20%; height: 10px;"><%= submit_tag "Edit Event", class: "btn btn-primary" %></p></center>
        </div>
      </form>
        <% end %>
  </div>
</body>

app/views/events/index.html.erb
<% if flash[:alert] != nil %>
    <div class='alert alert-success mt-4'>
       <center> <%= flash[:alert] %></center>
    </div>
  <%end%>
	
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" >
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%=image_tag ('eventbrite.jpg'), class:"d-block w-100" %>

    </div>
    <div class="carousel-item">
      <%=image_tag ('celeb.jpg'), class:"d-block w-100" %>
  
    </div>
    <div class="carousel-item">
      <%=image_tag ('yoga.jpg'), class:"d-block w-100" %>
    
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br>




<div class="body">

  <h2 style="color: #1e0a3c; margin-left: 30px; font-weight: bold;">Vivez le meilleur</h2>

	
<center>

  <%@event.all.reverse_each do |e|%>
  <a href="<%=event_path(e.id)%>" class="text-body" style="text-decoration: none;">
    <div class="card indexcard" style="width: 21rem;">
     <div class="card-img-top">
      <%if e.avatar.attached? == true%>
      <%=image_tag e.avatar, alt: 'photo de profil', size: '335x169', style: "border-radius: 10px 10px 0px 0px;"%>
      <%else%>
      <p style="height: 169px; margin-bottom: 0px; justify-content: center;">Ajoute une photo</p>
      <%end%>
    </div>
    <div class="card-body">
      <div class="titre" style="display: flex;">
        <span class="badge badge-white" style="margin-right:20px; font-size: .9rem;"><small style="color:orange;"><%=e.mois%></small><br><%=e.jour%></span>
        <p class="card-text my-text" style="font-size: 1.25rem; width: 80%;"><cente><%=e.title%> <br><% if e.is_free?%><span class="badge badge-danger">GRATUIT !</span><%end%></cente></p>
      </div>
      <small><p style="font-size: 10px;" class="text-secondary">
       <%if e.is_free? == false%>
       À partir de : <%=e.price%>.00 €
       <%end%>
       <br>
       <%=e.message_time%>, Durée : <%=e.duration%> min
       <br>
       <%= content_tag(:i, "", class: "fas fa-map-marker-alt text-body") %></i> <%=e.location%></p></small>
     </div>
   </div>
 </a>
 <%end%>
</center>

app/views/events/show.html.erb
<% if flash[:succes] != nil %>
<div class='alert alert-success mt-4'>
   <center> <%= flash[:succes] %></center>
</div>
<% end %>
<% if flash[:error] != nil %>
<div class='alert alert-danger mt-5'>
    <center> <%= flash[:error] %></center>
</div>
<% end %>
<div class="pricing-header px-2 py-3 pt-md-2 pb-md-2 mx-auto text-center" style="font-size: 1rem;">

      <h1 class="display-4"><%= @event.title%></h1>
      <p class="lead" style="font-size: 1rem;"><strong>Son lieu :</strong> <%=@event.location%></p>
  <p class="lead" style="font-size: 1rem;"><strong>Date de début :</strong> <%=@event.message_time%> | <strong>Durée :</strong> <%=@event.duration%> minutes</p>
  <p class="lead" style="font-size: 1rem;"><strong>Description :</strong> "<%=@event.description%>"</p>
  <p class="lead" style="font-size: 1rem;"><strong>Prix :</strong> <%=@event.price%> euros</p>
  <p class="lead" style="font-size: 1rem;"><strong>Créé par :</strong> <%=@event.admin.first_name%> / <%=@event.admin.email%></p>
  <p class="lead" style="font-size: 1rem;"><strong>Nombre de participants :</strong> <%=Attendance.where(event_id: params[:id]).count%></p>

<%if @event.admin == current_user%>
<%nil%>
<%elsif @event.users.include? current_user%>
 <p><strong>Vous participez à cet événement</strong></p>
<%else%>
  <%= form_tag event_subscribe_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation" style="height: 100px;">
        <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount lead">
      <span><strong>Amount:</strong> <%=@event.price%> €</span>
  </label>
</article>

<script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
data-description="A month's subscription"
data-amount="<%=@event.price * 100%>"
data-currency="eur"
data-locale="auto"></script>
<% end %> 
<%end%>


<br>
<%if @event.admin == current_user%>
<%=link_to "Editer cet événement", edit_event_path(@event), class:"stripe-button", style: "margin-right: 10px;"%>

<%= link_to "Supprimer cet événement", @event_destroy, :method => :delete, data: {confirm: "Are you sure ?"}, class:"stripe-button"%>
<%else%>
<%nil%>
<%end%>
 
<%if @event.admin == current_user%>
  <h6>Ajouter une photo ?</h6>
  <div>
      <br>
      <%= form_tag event_avatars_path(@event), multipart: true do %>
      <%= file_field_tag :avatar %>
      <%= submit_tag "Add" %>
      <% end %>
  </div>
  <%end%>
  <br>


  <p>Liste des participants :</p>   
<table class="table table-striped">
  <thead>
      <tr>
          <th>Nom</th>
          <th>Email</th>
          <th></th>
      </tr>
  </thead>
  <%@event.users.each do |u|%> 
  
  <tr>
      <td><%=u.first_name%></td>
      <td><%=u.email%></td>
      <td><%=link_to "Voir le profil", user_path(u.id)%></td>
  </tr>

  <%end%></table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CheapEventBrite</title>
    <script src="https://code.jquery.com/jquery-3.3.1.js"integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
  <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
 
  <%= favicon_link_tag asset_path('favicon.png') %>
  
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="<%=root_path%>" style="color: orange;" >
    CheapEventBrite
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown" id="navbarText">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="<%=new_event_path%>">Créer un événement <span class="sr-only">(current)</span></a>
      </li>
      
      <li class="nav-item">
        <a class="nav-link" href="">Contact</a>
      </li>
      <% if user_signed_in?%>
       <li class="nav-item">
        <a class="nav-link" href="<%=user_path(current_user.id)%>">Profile</a>
      </li>
      <li class="nav-item">
        <a class="nav-link text-body" href="<%=user_path(current_user.id)%>"><%=current_user.first_name if current_user.first_name.present?%></a>
      </li>
      <%end%>
    </ul> 
      <ul class="navbar-nav ml-auto">
      <%if !user_signed_in?%>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Sign in / Log in
        </a>
        <%else%>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle ml-auto" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Log out / Edit Profile
          </a><%end%>
         
          

          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%if !user_signed_in?%>
            <center><a class="dropdown-item" href="<%=new_user_registration_path%>" style="color: gray;">Sign in</a></center>
            <center><a class="dropdown-item" href="<%=new_user_session_path%>" style="color: gray;">Log in</a></center>
            <%else%>
            <center><%=link_to "Log out", destroy_user_session_path, method: :delete , data: {confirm: "Veux tu vraiment nous quitter ?"}, style:"color: gray; text-decoration: none;"%>
            </center>
            <br>
           <center><a href="<%=edit_user_path(current_user.id)%>" style="color: gray; text-decoration: none;">Edit Profile</a></center>
           <center><a href=""></a></center>
          </div>
        </li>
    
        <%end%>
      </ul>
    </div>
  </nav>
  <body>
    <div class="yield">
      <%= yield %>
    </div> 
  </body>
  <br>
   <footer class="footer" >
      <div class="container" style="display: flex; justify-content: space-between; flex-direction: row;">
         <div class="text-muted">
          <p>À propos</p>
         </div>
          <div class="text-muted">Qui sommes nous ?</div>
          <div class="text-muted">Nous contacter</div>
      </div>
    </footer>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<body>
<center>
  <h5>Edit your profile</h5>
</center>
   <div style="margin-left: 20px; display: flex; justify-content: space-between; margin-top: 50px;">

  <div class="form" style="width: 50%; margin-left: 100px;">
     
    <%=form_tag url_for(action: 'update'), method: "put" do %>
    <div class="form-group" style="margin-top: 20px; width: 80%;">
      <%= label_tag 'First_name' %>
      <br>
      <%= text_field_tag 'first_name', current_user.first_name, class: "form-control" %>
    </div>
    <div class="form-group" style="width: 80%;" >
      <%= label_tag 'Last_name' %>
      <br>
      <%= text_field_tag 'last_name', current_user.last_name, class: "form-control" %>
    </div>
    <br>
    <div class="form-group" style="width: 80%;">

      <%= submit_tag "Edit Profile", class: "btn btn-sm btn-primary", style: "width:100%" %>
    </div>
    <% end %>
  </div>  
    <div class="picture" style="width: 40%; margin-right: 70px;">
      <% if current_user.photo.attached? == true %>
      <h6>Changer d'avatar ?</h6>
       <%=image_tag @user.photo , size: "240x240" , style: "margin-bottom: 5px;" %>
     <%else%>
      <h6>Upload a picture</h6>
      <%end%>
      <div class="form-group" style="width: 60%;">
        <%= form_tag user_photos_path(@user), multipart: true do %>
        <%= file_field_tag :photo %>
        <%= submit_tag "Upate", class: "btn btn-sm btn-primary", style: "margin-top: 10px;"%>
      </div>
      <% end %>
    </div>
</div></center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
</body>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if flash[:alert] != nil %>
<div class='alert alert-success mt-4'>
 <center> <%= flash[:alert] %></center>
</div>
<%end%>
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <%if @user.photo.attached?%>
  <%=image_tag @user.photo , size: "250x250"  %>
  <%else%>
  <%=image_tag ('user.png'), size: '250x250'%>
  <%end%>
  <h1 class="display-4">Profil</h1>
  <p class="lead"> <%= @user.first_name %> </p>
  <p class="lead"> <%= @user.email %> </p>

  <% if current_user.id == @user.id %>
  <a style="margin-left: 20px; color: gray; text-decoration: none;"><%=link_to "Editer ton profil", edit_user_path(current_user.id) , style: "color: gray; text-decoration: none;" %></a>
  <%else%>
  <%nil%>
  <%end%>
</div>
<center>
<div style="margin-top: 10px;">
<h6>Tes événements :</h6>
</div>
<%@event.reverse_each do |e|%>
  <a href="<%=event_path(e.id)%>" class="text-body" style="text-decoration: none;">
    <div class="card indexcard" style="width: 21rem;">
     <div class="card-img-top">
      <%if e.avatar.attached? == true%>
      <%=image_tag e.avatar, alt: 'photo de profil', size: '335x169', style: "border-radius: 10px 10px 0px 0px;"%>
      <%else%>
      <p style="height: 169px; margin-bottom: 0px; justify-content: center;">Ajoute une photo</p>
      <%end%>
    </div>
    <div class="card-body">
      <div class="titre" style="display: flex;">
        <span class="badge badge-white" style="margin-right:20px; font-size: .9rem;"><small style="color:orange;"><%=e.mois%></small><br><%=e.jour%></span>
        <p class="card-text my-text" style="font-size: 1.25rem; width: 80%;"><cente><%=e.title%> <br><% if e.is_free?%><span class="badge badge-danger">GRATUIT !</span><%end%></cente></p>
      </div>
      <small><p style="font-size: 10px;" class="text-secondary">
       <%if e.is_free? == false%>
       À partir de : <%=e.price%>.00 €
       <%end%>
       <br>
       <%=e.message_time%>, Durée : <%=e.duration%> min
       <br>
       <%= content_tag(:i, "", class: "fas fa-map-marker-alt text-body") %></i> <%=e.location%></p></small>
     </div>
   </div>
 </a>
 <%end%>
</center>